apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d6zu5vspa-python
  janus-idp.io/tekton: d6zu5vspa-python
  backstage.io/kubernetes-id: d6zu5vspa-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d6zu5vspa-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
