apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: d6zu5vspa-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d6zu5vspa-python 
  name: d6zu5vspa-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: d6zu5vspa-python 
